version: '3.4'

services:
  FoodDeliveryAppClient:
    container_name: food-delivery-application-client
    image: "${IMAGE_NAME}"
    environment:
      NODE_ENV: production

    ports:
      - "3000:3000"
    restart: always

    networks:
      - food_delivery_network

# volumes:
#   node_modules_vol:

networks:
  food_delivery_network:
    driver: bridge 
