version: '3.4'

services:
  FoodDeliveryAppClient:
    container_name: food-delivery-application-client
    image: "${IMAGE_NAME}"
    environment:
      NODE_ENV: prod
    ports:
      - "3000:80"
    restart: always
    networks:
      - food_delivery_network

networks:
  food_delivery_network:
    driver: bridge 
