version: '3.4'

services:
  FoodDeliveryAppClient:
    container_name: food-delivery-application-client
    image: food-delivery-application-client:v0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      NODE_ENV: dev

    ports:
      - "3000:5173"

    volumes:
      - .:/app
      - node_modules_vol:/app/node_modules  

    networks:
      - food_delivery_network

volumes:
  node_modules_vol:

networks:
  food_delivery_network:
    driver: bridge 
